### ISSUE TITLE
VC lifecycle methods not called on dismiss for presentingViewController

### ISSUE THREAD

**Issue by larryonoff** [12207480/TYAlertController#1]
I analyzed the issue and it looks that there number of solutions here http://stackoverflow.com/questions/25488267/custom-transition-animation-not-calling-vc-lifecycle-methods-on-dismiss

My project has setting "View controller-based status bar appearance" enabled. So I cannot refresh status bar appearance when alert is dismissed.

**Comment by 12207480** [comment]
// dismiss controller completed block
@property (nonatomic, copy) void (^dismissComplete)(void);

this block will call， when viewController dismissed

**Comment by larryonoff** [comment]
@12207480 usage of ```dismissComplete``` is a workaround, but no solution, e.g. lifecycle methods are called by using ```UIAlertController``` from-the-box.
