### ISSUE TITLE
感谢作者大大!  想问一下,ButtonContentView  与  TextFieldContentView 之间是否可以加一个 padding ?  或者说 ButttonContentView 内部可以设置一个 padding?  目前想增加 message 与 button 的距离,不知如何是好. 

### ISSUE THREAD

**Issue by NapoleonBaiAndroid** [12207480/TYAlertController#10]

**Comment by NapoleonBaiAndroid** [comment]
NSLayoutConstraint *buttonTopConstraint = [alertView valueForKey:@"buttonTopConstraint"];
    buttonTopConstraint.constant = -15;
我不知道这样做是不是很好?或者说是我自己还没有找到相应的API 设置,还望指教.感谢

**Comment by 12207480** [comment]
我看看

**Comment by 12207480** [comment]
添加了属性 _buttonContentViewTop

**Comment by NapoleonBaiAndroid** [comment]
OK , 期待早日推送到cocoapods上,感谢
