### ISSUE TITLE
(Swift)分析友盟报错信息，发现这个地方有问题，麻烦看一下

### ISSUE THREAD

**Issue by xiaoxiongke** [12207480/TYAlertController#12]
![image](https://cloud.githubusercontent.com/assets/11352346/21210098/7b855654-c2b3-11e6-8121-a08d3a4797d7.png)

**Comment by 12207480** [comment]
好的 我看看

**Comment by 12207480** [comment]
swift ？

**Comment by 12207480** [comment]
![image](https://cloud.githubusercontent.com/assets/6346030/21211516/2ff3c822-c2bf-11e6-87ff-ee41f457215d.png)
 你是否使用buttonFont这个属性 搜下 
还需要更多的信息

**Comment by xiaoxiongke** [comment]
搜了下 没有使用。。
