### ISSUE TITLE
对TransitionAnimate只有.m存疑

### ISSUE THREAD

**Issue by 123let** [12207480/TYAlertController#16]
项目只有TYAlertController+TransitionAnimate.m 为什么没有.h不是很清楚.

**Comment by 12207480** [comment]
搜一下TransitionAnimate就看到了

**Comment by 123let** [comment]
都搜索了，还是没有，是在不行麻烦把.h 单独发我 我qq 834902615@qq.com
![qq20170629-2](https://user-images.githubusercontent.com/16968630/27681693-ae764742-5cf2-11e7-99dd-49ae14089035.png)
![qq20170629](https://user-images.githubusercontent.com/16968630/27681694-aeb8038a-5cf2-11e7-91a9-47c814090e42.png)

**Comment by 12207480** [comment]
没有单独分个.h  在
![image](https://user-images.githubusercontent.com/6346030/27723755-28f2f958-5da1-11e7-9884-9b2307afeed1.png)
