### ISSUE TITLE
kCurrentWindow 这个宏  改成keywindow才能显示出来  

### ISSUE THREAD

**Issue by achongGitHub** [12207480/TYAlertController#27]
//#define kCurrentWindow [[UIApplication sharedApplication].windows firstObject]
#define kCurrentWindow [UIApplication sharedApplication].keyWindow

有没有跟我遇到一样的情况啊

**Comment by JianWenXie** [comment]
有,自己写个分类,重写show方法,问题解决

**Comment by 12207480** [comment]
可以提个 pull request

**Comment by 12207480** [comment]
Fixed
