### ISSUE TITLE
TYShowAlertView 文件中.m 文件有错

### ISSUE THREAD

**Issue by JianWenXie** [12207480/TYAlertController#30]
#define kCurrentWindow [[UIApplication sharedApplication].windows firstObject] 
看你是这样取的当前currentWindow
可,在我层级比较复杂的时候,这样做就出问题,取的currenWindow就不是我当前的window
我自己写了个分类,重写了show方法
把currentWindow改成如下
[UIApplication sharedApplication].keyWindow
bug解决.

**Comment by 12207480** [comment]
Fixed
