### ISSUE TITLE
怎么获取 UItextFiled的回掉数据？

### ISSUE THREAD

**Issue by chihaodong** [12207480/TYAlertController#5]
Alert是非常漂亮，但是 怎么获取 回掉的数据？ 点击确认  怎么获取UITextField数据？ 这个 看了代码 没有获取的方式，只是展示了 响应的样式而已。。。。。。

**Comment by FayeXuNJ** [comment]
@chihaodong  你傻

**Comment by 12207480** [comment]
![image](https://cloud.githubusercontent.com/assets/6346030/17849221/62915356-688a-11e6-848d-4304f7e7cbb5.png)
